name: country_calling_code_picker
description: Flexible Country picker for getting Country code and Calling code.
version: 2.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_sim_country_code: 
    git:
      url: https://github.com/elieonline/flutter_sim_country_code.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flags/
    - raw/
